#!/bin/bash
source "$HOME/scripts/colors"

echo -e "${C_CELESTE}Battery Status:${C_RESET}"
upower -i $(upower -e | grep 'BAT') | grep -E "state|percentage|energy-full-design|energy-full"

echo -e "${C_AZUL}CPU USAGE and TEMPERATURE:${C_RESET}"
top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print "CPU USE: " 100-$1 "%"}'

sensors | grep "Core"
